version: '2'
services:
  nginx:
    build: ./nginx/.
    environment:
      - BASIC_AUTH_USERNAME=test
      - BASIC_AUTH_PASSWORD=test
    ports:
      - "80:80"
    links:
      - fluentd
      - kibana
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.access

  fluentd:
    build: ./fluentd/.
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
